### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by gunner-n** [andrewRowlinson/mplsoccer#31]
Hi, 

I apologize if this is not the right place. I am new to Python Programming. I am trying to install mplsoccer using pip and getting an error. It must be something I am doing wrong. Appreciate any help I can get for this. 

pip install mplsoccer

    ERROR: Command errored out with exit status 1:
     command: 'c:\python\python394\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\naman\\AppData\\Local\\Temp\\pip-install-z8r0sc11\\mplsoccer_07f310df0dd94fbb840e04b488eebeb9\\setup.py'"'"'; __file__='"'"'C:\\Users\\naman\\AppData\\Local\\Temp\\pip-install-z8r0sc11\\mplsoccer_07f310df0dd94fbb840e04b488eebeb9\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\naman\AppData\Local\Temp\pip-pip-egg-info-guzrhz9z'
         cwd: C:\Users\naman\AppData\Local\Temp\pip-install-z8r0sc11\mplsoccer_07f310df0dd94fbb840e04b488eebeb9\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\naman\AppData\Local\Temp\pip-install-z8r0sc11\mplsoccer_07f310df0dd94fbb840e04b488eebeb9\setup.py", line 3, in <module>
        import mplsoccer
      File "C:\Users\naman\AppData\Local\Temp\pip-install-z8r0sc11\mplsoccer_07f310df0dd94fbb840e04b488eebeb9\mplsoccer\__init__.py", line 5, in <module>
        from mplsoccer.pitch import *
      File "C:\Users\naman\AppData\Local\Temp\pip-install-z8r0sc11\mplsoccer_07f310df0dd94fbb840e04b488eebeb9\mplsoccer\pitch.py", line 7, in <module>
        from mplsoccer._pitch_plot import BasePitchPlot
      File "C:\Users\naman\AppData\Local\Temp\pip-install-z8r0sc11\mplsoccer_07f310df0dd94fbb840e04b488eebeb9\mplsoccer\_pitch_plot.py", line 8, in <module>
        import seaborn as sns
    ModuleNotFoundError: No module named 'seaborn'

**Comment by andrewRowlinson** [comment]
mplsoccer requires seaborn too along with some other requirements (https://github.com/andrewRowlinson/mplsoccer/blob/master/requirements.txt). You can install seaborn via: pip install seaborn.

**Comment by gunner-n** [comment]
Resolved!! Thank you so much!
